include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use: ignore
    curly_braces_in_flow_control_structures: ignore
    use_build_context_synchronously: ignore
    avoid_print: ignore
    unnecessary_to_list_in_spreads: ignore
